"""Updated migration after reset

Revision ID: b72fdb3387b1
Revises: 
Create Date: 2025-02-21 13:51:53.467915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b72fdb3387b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profession_relations')
    op.drop_table('keywords')
    op.drop_table('my_app_image')
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professions_name'), ['name'], unique=False)
        batch_op.drop_constraint('professions_relevant_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professions', schema=None) as batch_op:
        batch_op.create_foreign_key('professions_relevant_fkey', 'professions', ['relevant'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_professions_name'))

    op.create_table('my_app_image',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='my_app_image_pkey')
    )
    op.create_table('keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='keywords_pkey'),
    sa.UniqueConstraint('keyword', name='keywords_keyword_key')
    )
    op.create_table('profession_relations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profession_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_profession_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], name='profession_relations_profession_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_profession_id'], ['professions.id'], name='profession_relations_related_profession_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profession_relations_pkey')
    )
    # ### end Alembic commands ###
